### ISSUE TITLE
Can't read clientraw from URL

### ISSUE THREAD

**Issue by sfeakes** [waynedgrant/json-webservice-wdlive#5]
May I suggest you change line 20 in BaseClientRaw.php 
-- from --
if (is_readable($path))

-- to --
if (is_readable($path) || filter_var($path, FILTER_VALIDATE_URL))

That way you can use a URL in the config file for a meteohub installation and not have to ftp files around.
ie, in config.php
define("CLIENT_RAW_DIRECTORY", "http://meteohub-machine-name/live/");

**Comment by waynedgrant** [comment]
Apologies, I didn't see this issue before today.

Excellent suggestion. I've pushed a changed to master to support this.
